version: '3.1'

services:
  sitebrecho:
    container_name: sitebrecho
    image: sitebrecho
    build:
      context: .
    command: python manage.py tailwind start
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
